CREATE OR REPLACE VIEW cf_logs_view_friendly AS
SELECT
  year, month, day, hour,
  date, time, x_edge_location,
  sc_bytes,
  c_ip,
  cs_method           AS method,
  cs_host             AS host,
  cs_uri_stem         AS uri_stem,
  cs_uri_query        AS uri_query,
  sc_status           AS status,
  cs_referer          AS referer,
  cs_user_agent       AS user_agent,
  x_edge_result_type,
  x_host_header,
  cs_protocol,
  cs_bytes            AS client_bytes,
  time_taken,
  x_forwarded_for,
  ssl_protocol,
  ssl_cipher,
  x_edge_response_result_type,
  cs_protocol_version,
  fle_status,
  fle_encrypted_fields,
  c_port,
  time_to_first_byte,
  x_edge_detailed_result_type,
  sc_content_type,
  sc_content_len,
  sc_range_start,
  sc_range_end
FROM cf_logs_view;
